# permissions for end users to edit mysqlbackupstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysqlbackupstore-editor-role
rules:
- apiGroups:
  - m1kcloud.m1k.cloud
  resources:
  - mysqlbackupstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - m1kcloud.m1k.cloud
  resources:
  - mysqlbackupstores/status
  verbs:
  - get
