# permissions for end users to edit mysqlbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysqlbackup-editor-role
rules:
- apiGroups:
  - m1kcloud.m1k.cloud
  resources:
  - mysqlbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - m1kcloud.m1k.cloud
  resources:
  - mysqlbackups/status
  verbs:
  - get
