# permissions for end users to view mysqlrestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysqlrestore-viewer-role
rules:
- apiGroups:
  - m1kcloud.m1k.cloud
  resources:
  - mysqlrestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - m1kcloud.m1k.cloud
  resources:
  - mysqlrestores/status
  verbs:
  - get
