# permissions for end users to edit mysqlrestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysqlrestore-editor-role
rules:
- apiGroups:
  - m1kcloud.m1k.cloud
  resources:
  - mysqlrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - m1kcloud.m1k.cloud
  resources:
  - mysqlrestores/status
  verbs:
  - get
