
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - m1kcloud.m1k.cloud
  resources:
  - mysqlbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - m1kcloud.m1k.cloud
  resources:
  - mysqlbackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - m1kcloud.m1k.cloud
  resources:
  - mysqlbackupstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - m1kcloud.m1k.cloud
  resources:
  - mysqlbackupstores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - m1kcloud.m1k.cloud
  resources:
  - mysqlclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - m1kcloud.m1k.cloud
  resources:
  - mysqlclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - m1kcloud.m1k.cloud
  resources:
  - mysqlrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - m1kcloud.m1k.cloud
  resources:
  - mysqlrestores/status
  verbs:
  - get
  - patch
  - update
