apiVersion: m1kcloud.m1k.cloud/v1alpha1
kind: MysqlBackup
metadata:
  generateName: mysqlbackup-
  namespace: database
spec:
  clusterRef:
    clusterStatus: Ready
    clusterName: mysql-cluster-m1k
  secretRef:
    secret: mysql-cluster-m1k
  database: test_do_not_exist
  storageRef:
    storageProvider: s3
    region: us-west-1
    bucket: michele-test-backup-operator
  maxJobs: 3
  backupType: mysqldump
  host: 10.106.171.2
  port: "3306"
  username: root
