apiVersion: m1kcloud.m1k.cloud/v1alpha1
kind: MysqlBackup
metadata:
  generateName: mysqlbackup-
  #name: mysqlbackup
  namespace: database
spec:
  initState: newBackup
  clusterRef:
    clusterStatus: Ready
    clusterName: mysql-cluster-m1k
  secretRef:
    secret: mysql-cluster-m1k
  databasesToBackup:
    - puppaaaa
    - test
  storageRef:
    storageProvider: s3
    region: us-west-1
    bucket: michele-test-backup-operator
  backupType: mysqldump
  host: 10.106.171.2
  port: "3306"
  username: root
